### ISSUE TITLE
City on User Model

### ISSUE THREAD

**Issue by ronathan** [JeffMBernstein/synapsABILITY#1]
Do we still need a user to have a city property?

**Comment by gattik** [comment]
Doesn't it matter for gmaps?

On Sun, Nov 3, 2013 at 6:05 PM, Ronald Victorino
notifications@github.comwrote:

> Do we still need a user to have a city property?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/JeffMBernstein/synapsABILITY/issues/1
> .

## 

Kathleen Gatti
Ryerson University, Toronto
web kathleengatti.com
tel 647-971-9687

**Comment by ronathan** [comment]
I'm not really sure, but for some reason it's missing in our schema. I did a drop and a create/migrate and no city. I was just wondering if we took it out for any particular reason.

If not, then I'll add it back. =)
